### ISSUE TITLE
Private Query exception when doing SUM or COUNT query on empty database

### ISSUE THREAD

**Issue by ankit-oss** [privacytoolsproject/burdock#75]
**Repro Steps**
ag = agg.Aggregation(t=1, repeat_count=10000)
query_str = "SELECT SUM(Usage) AS TotalUsage FROM "
res_list = self.dp_powerset_test(query_str, plot=False)

Within powerset_test, we can invoke below commands and create empty datasets [0_0, 1_1, 2_2] - 

        ag = agg.Aggregation(t=1, repeat_count=repeat_count)
        ex = exp.Exploration()
        ex.generate_powerset(ex.df)
        res_list = {}
        for filename in ex.visited:
            if(filename not in ["0_0", "1_1", "2_2"]):
                d1_query = query_str + "d1_" + filename + "." + "d1_" + filename
                d2_query = query_str + "d2_" + filename + "." + "d2_" + filename
                d1 = pd.read_csv(os.path.join(ex.file_dir, ex.csv_path , "d1_" + filename + ".csv"))
                d2 = pd.read_csv(os.path.join(ex.file_dir, ex.csv_path , "d2_" + filename + ".csv"))
                d1_yaml_path = os.path.join(ex.file_dir, ex.csv_path , "d1_" + filename + ".yaml")
                d2_yaml_path = os.path.join(ex.file_dir, ex.csv_path , "d2_" + filename + ".yaml")
                fD1, fD1_bounds = ag.run_agg_query(d1, d1_yaml_path, d1_query, confidence)
                fD2, fD2_bounds = ag.run_agg_query(d2, d2_yaml_path, d2_query, confidence)

0_0 means D1 has 1 row of 0 index and D2 has that dropped. So D2 is empty database. run_agg_query crashes on this line - 

fD2, fD2_bounds = ag.run_agg_query(d2, d2_yaml_path, d2_query, confidence)

**Error**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-eb648738bff6> in <module>
      1 start_time = time.time()
      2 query_str = "SELECT COUNT(UserId) AS TotalUsage FROM "
----> 3 res_list = dv.dp_powerset_test(query_str, plot=False)
      4 print("DP Powerset Test: ", res_list)
      5 print("--- %s seconds ---" % (time.time() - start_time))

/e/Git/burdock/evaluation/DPVerification.py in dp_powerset_test(self, query_str, debug, plot, bound, exact, repeat_count, confidence)
    309                 d2_yaml_path = os.path.join(ex.file_dir, ex.csv_path , "d2_" + filename + ".yaml")
    310                 fD1, fD1_bounds = ag.run_agg_query(d1, d1_yaml_path, d1_query, confidence)
--> 311                 fD2, fD2_bounds = ag.run_agg_query(d2, d2_yaml_path, d2_query, confidence)
    312                 acc_res = self.accuracy_test(fD1, fD1_bounds, confidence)
    313                 d1hist, d2hist, bin_edges = self.generate_histogram_neighbors(fD1, fD2, binsize="auto")

/e/Git/burdock/evaluation/Aggregation.py in run_agg_query(self, df, metadata_path, query, confidence)
     57         reader = CSVReader(metadata, df)
     58         private_reader = PrivateQuery(reader, metadata, self.epsilon)
---> 59         exact_values = private_reader._execute_exact(query)
     60         bounds_centered_zero = list(private_reader._apply_noise(*exact_values, confidence)[1].values())[1]
     61         actual_value = exact_values[-1].rows()[1:][0][1]

/e/Git/burdock/sdk/burdock/query/sql/private/query.py in _execute_exact(self, query_string)
    111 
    112         # execute the subquery against the backend and load in typed rowset
--> 113         srs = self.reader.execute_typed(subquery)
    114         return (subquery, query, syms, types, sens, srs)
    115 

/e/Git/burdock/sdk/burdock/query/sql/reader/csv_reader.py in execute_typed(self, query)
     50             query_string = str(query)
     51         rows = self.execute(query_string)
---> 52         return TypedRowset(rows, types, sens)
     53 

/e/Git/burdock/sdk/burdock/query/sql/reader/rowset.py in __init__(self, rows, types, sens)
     53                 tempcols[cn].append(row[idx])
     54         for cn in self.colnames:
---> 55             self[cn] = tempcols[cn]
     56 
     57         # verify all lengths the same

/e/Git/burdock/sdk/burdock/query/sql/reader/rowset.py in __setitem__(self, key, value)
     97                 self.m_cols[cn] = np.array(value).astype(bool)
     98             elif t == "int":
---> 99                 self.m_cols[cn] = np.array(value).astype(int)
    100             elif t == "float":
    101                 self.m_cols[cn] = np.array(value).astype(float)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by joshua-oss** [comment]
This appears to be using an old version of query that doesn't have _preprocess and _postprocess.  Can you make sure you are merged from latest master?  I added a bunch of unit tests and cannot repro.

**Comment by joshua-oss** [comment]
FYI, unit tests for this scenario are here: https://github.com/privacytoolsproject/burdock/pull/79/files

If issue does not repro in latest master, you can close this issue

**Comment by ankit-oss** [comment]
I tried this on latest master but still encountering this issue. Below are the YAML and Datasets I used - 

**YAML**

Database:
  d2_2_2:
    d2_2_2:
      rows: 0
      UserId:
        type: string
        is_key: True
      Usage:
        type: int
        min: 10000
        max: 10001

**Dataset**

UserId,Usage

**Error**
Logged in [Jupyter notebook](https://github.com/ankit-oss/burdock/blob/master/evaluation/Differential%20Privacy%20Verification.ipynb) at the end

Testing:  2_2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-eb648738bff6> in <module>
      1 start_time = time.time()
      2 query_str = "SELECT COUNT(UserId) AS TotalUsage FROM "
----> 3 res_list = dv.dp_powerset_test(query_str, plot=False)
      4 print("DP Powerset Test: ", res_list)
      5 print("--- %s seconds ---" % (time.time() - start_time))

~/burdock/evaluation/DPVerification.py in dp_powerset_test(self, query_str, debug, plot, bound, exact, repeat_count, confidence)
    312             d2_yaml_path = os.path.join(ex.file_dir, ex.csv_path , "d2_" + filename + ".yaml")
    313             fD1 = ag.run_agg_query(d1, d1_yaml_path, d1_query, confidence)
--> 314             fD2 = ag.run_agg_query(d2, d2_yaml_path, d2_query, confidence)
    315             #acc_res = self.accuracy_test(fD1, fD1_bounds, confidence)
    316             acc_res = None

~/burdock/evaluation/../evaluation/Aggregation.py in run_agg_query(self, df, metadata_path, query, confidence)
     58         private_reader = PrivateQuery(reader, metadata, self.epsilon)
     59         query_ast = private_reader.parse_query_string(query)
---> 60         subquery_results = private_reader._preprocess(query_ast)
     61 
     62         #exact_values = private_reader.execute_ast(query)

~/burdock/sdk/burdock/query/sql/private/query.py in _preprocess(self, query)
     79 
     80         # execute the subquery against the backend and load in typed rowset
---> 81         srs = self.reader.execute_typed(subquery)
     82         return (subquery, query, syms, types, sens, srs)
     83 

~/burdock/sdk/burdock/query/sql/reader/csv_reader.py in execute_typed(self, query)
     50             query_string = str(query)
     51         rows = self.execute(query_string)
---> 52         return TypedRowset(rows, types, sens)
     53 

~/burdock/sdk/burdock/query/sql/reader/rowset.py in __init__(self, rows, types, sens)
     53                 tempcols[cn].append(row[idx])
     54         for cn in self.colnames:
---> 55             self[cn] = tempcols[cn]
     56 
     57         # verify all lengths the same

~/burdock/sdk/burdock/query/sql/reader/rowset.py in __setitem__(self, key, value)
     97                 self.m_cols[cn] = np.array(value).astype(bool)
     98             elif t == "int":
---> 99                 self.m_cols[cn] = np.array(value).astype(int)
    100             elif t == "float":
    101                 self.m_cols[cn] = np.array(value).astype(float)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by joshua-oss** [comment]
OK, I think I found it.  When doing a SUM or COUNT on an empty rowset, the result shoul be 1 row (not empty), with value of 0 or NULL respectively.  Please try with the updated no_tau branch and ensure that it works.

**Comment by ankit-oss** [comment]
Thanks for the fix Josh! I pulled from no_tau branch and I don't see this issue anymore. Query is able to run successfully for empty databases.
