### ISSUE TITLE
DP Histogram test failing for SUM, COUNT, MEAN, VAR queries

### ISSUE THREAD

**Issue by ankit-oss** [privacytoolsproject/burdock#81]
Repro Steps
1. Run the DP predicate tests added in tests/evaluation folder
2. The result plots can be seen in this [notebook](https://github.com/ankit-oss/burdock/blob/master/evaluation/Differential%20Privacy%20Verification.ipynb) for SUM and COUNT queries

I'll add tests for mechanism to see if this is because of mechanism. For now, this includes testing the singleton SQL queries using a mock neighboring datasets D1 of size 10000  following geometric distribution and randomly removing 1 record to make D2 of size 9999. 

Pull request #71 has all the changes that include the pytest tests.

**Comment by joshua-oss** [comment]
The tests pass when we run the actual query 10,000 times.  The issue is that _postprocess is running repeatedly on the same copy of the data, which keeps adding noise on top of the previously noisy data.

**Comment by joshua-oss** [comment]
Please verify fix in latest checkin to powerset_test

**Comment by joshua-oss** [comment]
I noticed you had merged powerset_test into mechanism_test, so I pushed the fix to that branch.  You can test from there.

**Comment by ankit-oss** [comment]
Thanks so much Josh! Couldn't have figured it myself. Needed a new TypedRowset of original preprocessed data instead of passing by reference the previous iteration's preprocessed result on every subsequent postprocessed call. 

DP Predicate Test is now passing for all four singleton queries - SUM, COUNT, MEAN, VAR. 

10 of the 12 edges of database search graph for 3-D point are also passing for a singleton SUM query except the case where we have a neighbor pair that is single record database (let's say having Usage as 10000) vs empty record database (no rows). That we can investigate later. In that case, f(D1) is bounding f(D2) but not vice versa.
